sudo: required
services:
  - docker

script:
  - docker build -t leanderlindahl/node .
  - docker images leanderlindahl/node

before_deploy:
  - docker login -u $DOCKER_USER -p $DOCKER_PASS

deploy:
  provider: script
  script: docker push leanderlindahl/docker-travis
  on: 
    branch: master